title: Just the Docs Exercise
description: Just the Docs Exercise
theme: just-the-docs
color_scheme: dark
favicon_ico: "/images/favicon.ico"

url: https://beaskoczy.github.io/templatka-just

aux_links:
  Template Repository: https://github.com/beaskoczy/templatka-just
