title: Just the Docs Exercise
description: Just the Docs Exercise
theme: just-the-docs

url: https://beaskoczy.github.io/templatka-just

aux_links:
  Template Repository: https://github.com/beaskoczy/templatka-just
